apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
      default: main
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: pipeline-workspace
    - name: deploy
      runAfter: [clone]
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            kubectl apply -f deploy/deployment.yaml
            kubectl rollout status deployment/accounts
      workspaces:
        - name: source
          workspace: pipeline-workspace
